default["apache"]["sites"]["clowns"] = { "port" => 80}
default["apache"]["sites"]["bears"] = { "port" => 81}
default["apache"]["sites"]["x1"] = { "port" => 82}
default["apache"]["sites"]["x2"] = { "port" => 83}
default["apache"]["sites"]["x3"] = { "port" => 84}
default["apache"]["sites"]["x4"] = { "port" => 85}
default["apache"]["sites"]["x5"] = { "port" => 86}
default["apache"]["sites"]["x6"] = { "port" => 87}
default["apache"]["sites"]["x7"] = { "port" => 88}
default["apache"]["sites"]["x8"] = { "port" => 89}